# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded app-autoApp 7.9 [list source [file join $dir autoApp.tcl]]
package ifneeded autoAppActionFunc 7.8 [list source [file join $dir autoAppActionFunc.tcl]]
package ifneeded autoAppSysFunc 2.1 [list source [file join $dir autoAppSysFunc.tcl]]
package ifneeded autoAppAlmFunc 1.0 [list source [file join $dir autoAppAlmFunc.tcl]]
package ifneeded autoAppPubFunc 1.0 [list source [file join $dir autoAppPubFunc.tcl]]
package ifneeded autoAppAuthFunc 1.0 [list source [file join $dir autoAppAuthFunc.tcl]]
